##
## EPITECH PROJECT, 2021
## arcade
## File description:
## Makefile
##

all:
	$(MAKE) -C menu
	$(MAKE) -C pacman
	$(MAKE) -C nibbler
	$(MAKE) -C solarfox

clean:
	$(MAKE) -C menu clean
	$(MAKE) -C pacman clean
	$(MAKE) -C nibbler clean
	$(MAKE) -C solarfox clean

fclean:	clean
	$(MAKE) -C menu fclean
	$(MAKE) -C pacman fclean
	$(MAKE) -C nibbler fclean
	$(MAKE) -C solarfox fclean
