##
## EPITECH PROJECT, 2021
## arcade
## File description:
## Makefile
##

all:
	$(MAKE) -C pacman
	$(MAKE) -C nibbler

clean:
	$(MAKE) -C pacman clean
	$(MAKE) -C nibbler clean

fclean:	clean
	$(MAKE) -C pacman fclean
	$(MAKE) -C nibbler fclean