##
## EPITECH PROJECT, 2021
## arcade
## File description:
## Makefile
##

all:
	$(MAKE) -C ncurses
	$(MAKE) -C sdl2
	$(MAKE) -C sfml

clean:
	$(MAKE) -C ncurses clean
	$(MAKE) -C sdl2 clean
	$(MAKE) -C sfml clean

fclean:	clean
	$(MAKE) -C ncurses fclean
	$(MAKE) -C sdl2 fclean
	$(MAKE) -C sfml fclean